### ISSUE TITLE
Add location

### ISSUE THREAD

**Issue by Ana06** [Ana06/medical-data-android#12]
Store and send information about location to the database as it can improve predictions significantly.

**Comment by njacot** [comment]
I could work on that one if you are interested?

**Comment by Ana06** [comment]
Sure! :smile: 
I didn't add the _PRs welcome_ label to this issue because it involves more job than the others, but of course you can work on it. Location is a really valuable data.

We want to collect the location as frequently as possible without having a big impact in the battery. This data should be sent to the same MongoDB database than the daily test but to a different collection. It could be sent once a day for example.

Thank you! :wink:

**Comment by njacot** [comment]
Great! 
I will take a look this week what I can do. :)
